services:
  php74_calendarar:
    container_name: php74_calendarar
    build:
      context: .
      dockerfile: ./.docker/PHP74_Dockerfile
    volumes:
      - ./src:/var/www/html/src
      - ./tests:/var/www/html/tests
      - ./composer.json:/var/www/html/composer.json
      - ./phpunit.xml:/var/www/html/phpunit.xml
      - ./.docker:/var/www/html/.docker
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
    # restart: unless-stopped
    init: true
    command: /var/www/html/.docker/sh/test.sh

networks:
  internal:
