services:
  php74_calendarar_development:
    container_name: php74_calendarar_development
    build:
      context: .
      dockerfile: ./.docker/PHP74_Dockerfile
    volumes:
      - .:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini-development
    restart: unless-stopped
    init: true
    command: >
      bash -c '
        composer update;
        tail -f /dev/null;
      '
