version: "3.8"
services:
  php74_calendarar:
    container_name: php74_calendarar
    build:
      context: .
      dockerfile: ./.docker/PHP74_Dockerfile
    volumes:
      - .:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
    # restart: unless-stopped
    init: true
    command: vendor/bin/phpunit

  php80_calendarar:
    container_name: php80_calendarar
    build:
      context: .
      dockerfile: ./.docker/PHP80_Dockerfile
    volumes:
      - .:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
    # restart: unless-stopped
    init: true
    command: vendor/bin/phpunit
    depends_on:
      - php74_calendarar

  php81_calendarar:
    container_name: php81_calendarar
    build:
      context: .
      dockerfile: ./.docker/PHP81_Dockerfile
    volumes:
      - .:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
    # restart: unless-stopped
    init: true
    command: vendor/bin/phpunit
    depends_on:
      - php80_calendarar

  php82_calendarar:
    container_name: php82_calendarar
    build:
      context: .
      dockerfile: ./.docker/PHP82_Dockerfile
    volumes:
      - .:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
    # restart: unless-stopped
    init: true
    command: vendor/bin/phpunit
    depends_on:
      - php81_calendarar

  php83_calendarar:
    container_name: php83_calendarar
    build:
      context: .
      dockerfile: ./.docker/PHP83_Dockerfile
    volumes:
      - .:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
    # restart: unless-stopped
    init: true
    command: vendor/bin/phpunit
    depends_on:
      - php82_calendarar
